import assert from 'node:assert/strict';
import {validateAlbumProcess,validateAlbumPhoto,comparePhotoProcess,photoCanUpload} from '../src/donePickAlbumRules.ts';
assert.equal(validateAlbumProcess(' 295845 '),'295845');
assert.equal(validateAlbumProcess('292168'),'292168');
for(const value of ['','123','12345678901','0','000000','ABC123','292-168'])assert.throws(()=>validateAlbumProcess(value),/Process No/);
for(const type of ['image/jpeg','image/png','image/webp'])validateAlbumPhoto({type,size:5*1024*1024});
for(const input of [{type:'image/gif',size:1000},{type:'application/pdf',size:1000},{type:'image/png',size:0},{type:'image/jpeg',size:5242881}])assert.throws(()=>validateAlbumPhoto(input),/photo|photo|Each photo|Upload JPG/);
const detected=(no)=>({status:'detected',process:no,candidates:[no],confidence:85});
assert.equal(comparePhotoProcess(detected('295845'),'295845'),'matched');
assert.equal(comparePhotoProcess(detected('258965'),'295845'),'mismatch');
assert.equal(comparePhotoProcess({status:'ambiguous',process:'',candidates:['295845','296000']},'295845'),'ambiguous');
assert.equal(comparePhotoProcess({status:'missing',process:'',candidates:[]},'295845'),'unreadable');
assert.equal(comparePhotoProcess(null,'295845'),'unreadable');
assert.equal(photoCanUpload('matched',false),true);
assert.equal(photoCanUpload('mismatch',true),false,'Even an approved checkbox must not bypass a definite mismatch');
assert.equal(photoCanUpload('unreadable',false),false);
assert.equal(photoCanUpload('unreadable',true),true);
assert.equal(photoCanUpload('ambiguous',false),false);
assert.equal(photoCanUpload('ambiguous',true),true);
console.log('PASS: 11 OCR Process No. comparison and manual-review safety checks');
console.log('PASS: Process No. and multi-photo upload validation');
