import { useState } from 'react';
import { Mail, Truck, Send, FileText, CheckCircle2, AlertTriangle, Clock3, ArrowRight, Search, Paperclip, ShieldCheck } from 'lucide-react';
type RecordItem = { id:string; process:string; party:string; invoice:string; docs:number; status:string; email:boolean; tracking:boolean; bill:boolean };
type Props = { page:string; records:RecordItem[]; onNotice:(s:string)=>void };
const flow = {
  email: ['Link Outlook .EML conversation','Verify recipient & original thread','Prepare reply and document attachments','Continue email via office worker','Confirm sent result and save history'],
  tracking: ['Identify carrier and LR / docket number','Queue carrier website tracking','Read shipment status and capture evidence','Handle In Transit / Delivered / RTO / Exception','If delivered, make proof eligible for DataDoc'],
  bill: ['Validate invoice, E-Invoice and payment type','Run initial DataDoc dispatch transaction','Attach E-Invoice through Add Docs','Attach E-Way Bill when configured threshold applies','Verify partial successes before retry'],
  proof: ['Confirm delivered status','Check tracking evidence screenshot','Queue DataDoc tracking-proof submission','Verify result and preserve audit history']
};
function Workflow({steps}:{steps:string[]}){return <div className='legacy-flow'>{steps.map((s,i)=><div className='legacy-step' key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p>{i<steps.length-1&&<ArrowRight size={15}/>}</div>)}</div>}
export default function LegacyWorkflows({page,records,onNotice}:Props){
 const [submitTab,setSubmitTab]=useState('Bill Submitted');
 const [selected,setSelected]=useState('');
 const [emailThread,setEmailThread]=useState('');
 const [carrier,setCarrier]=useState('TCI');
 const [lr,setLr]=useState('');
 const [attachment,setAttachment]=useState('');
 const isEmail=page==='Email Process';
 const isTracking=page==='Tracking Delivery';
 const kind=isEmail?'email':isTracking?'tracking':submitTab==='Tracking Submit'?'proof':submitTab==='Email Submit'?'email':'bill';
 const visible=records.filter(r=>isEmail?r.email:isTracking?r.tracking:submitTab==='Email Submit'?r.email:submitTab==='Tracking Submit'?r.tracking:r.bill);
 return <section className='legacy-workspace'>
 <div className='legacy-banner'><div className='legacy-icon'>{isEmail?<Mail/>:isTracking?<Truck/>:<Send/>}</div><div><strong>Original PJS workflow · New OMS interface</strong><p>The operational sequence is retained from PJS. This is a safe preview; DataDoc, Outlook and courier automations are not connected.</p></div><span className='legacy-offline'><span/>Worker offline</span></div>
 {page==='Submit All Process'&&<div className='legacy-tabs'>{['Bill Submitted','Email Submit','Tracking Submit'].map(t=><button className={submitTab===t?'chosen':''} onClick={()=>{setSubmitTab(t);setSelected('')}} key={t}>{t}</button>)}</div>}
 <div className='legacy-grid'><div className='legacy-box'><div className='legacy-title'><div><small>PROCESS QUEUE</small><h2>{isEmail?'Email to Client':isTracking?'Dispatch Tracking':submitTab}</h2></div><span className='legacy-count'>{visible.length} transferred</span></div><p className='legacy-help'>Transfer records from Data Store to make them appear in this queue.</p>{visible.length===0?<div className='legacy-empty'><FileText size={25}/><b>No transferred records yet</b><span>Open Data Store → Transfer → choose this workflow.</span></div>:visible.map(r=><button key={r.id} className={'legacy-row '+(selected===r.id?'chosen':'')} onClick={()=>setSelected(r.id)}><span className='legacy-row-icon'><FileText size={18}/></span><span><b>{r.process}</b><small>{r.party}</small></span><span className='legacy-pill'>Pending</span><ArrowRight size={15}/></button>)}</div><div className='legacy-box'><div className='legacy-title'><div><small>WORKFLOW STEPS</small><h2>{kind==='email'?'Existing Outlook conversation':kind==='tracking'?'Carrier tracking':kind==='bill'?'DataDoc Bill Submit':'DataDoc Tracking Proof'}</h2></div><ShieldCheck size={20} color='#5475c4'/></div><Workflow steps={flow[kind]}/></div></div>
 {false && <div className='legacy-box legacy-form'><div className='legacy-title'><div><small>PROCESS DETAILS</small><h2>{isEmail?'Prepare customer email':isTracking?'Tracking details':kind==='bill'?'Bill submission review':kind==='proof'?'Tracking-proof review':'Email submission review'}</h2></div><span className='legacy-pill'>Preview only</span></div><div className='legacy-fields'><label>Selected process<select value={selected} onChange={e=>setSelected(e.target.value)}><option value=''>Select transferred process</option>{visible.map(r=><option key={r.id} value={r.id}>{r.process} — {r.party}</option>)}</select></label>{kind==='email'?<><label>Outlook conversation (.EML)<input type='file' accept='.eml' onChange={e=>setEmailThread(e.target.files?.[0]?.name||'')}/>{emailThread&&<small>Selected: {emailThread}</small>}</label><label>Email mode<select><option>Continue existing Outlook reply thread</option><option>Review linked conversation</option></select></label></>:kind==='tracking'?<><label>Transporter<select value={carrier} onChange={e=>setCarrier(e.target.value)}>{['TCI','VExpress','DTDC','Other configured carrier'].map(c=><option key={c}>{c}</option>)}</select></label><label>LR / Docket Number<input value={lr} onChange={e=>setLr(e.target.value)} placeholder='Enter or verify LR number'/></label></>:<><label>Submission stage<select><option>{kind==='bill'?'Initial transaction + Add Docs':'Delivered tracking evidence'}</option></select></label><label>Supporting document<input type='file' accept='.pdf,image/*' onChange={e=>setAttachment(e.target.files?.[0]?.name||'')}/>{attachment&&<small>Selected: {attachment}</small>}</label></>}</div><div className='legacy-actions'><span><AlertTriangle size={16}/> Office worker integration required for real actions</span><button onClick={()=>onNotice('Workflow preview only. No Outlook message, carrier tracking or DataDoc submission has been executed.')}><CheckCircle2 size={16}/> Review workflow</button></div></div>}
 <div className='legacy-note'><Clock3 size={18}/> Legacy behavior to preserve: retries must check actual results first, document uploads need verification, and every action needs an audit trail.</div>
 </section>;
}