import {useState} from 'react';
import {Upload,RefreshCw,Mail,PackageCheck,FileCheck2,AlertTriangle,Truck,CheckCircle2,Square,ChevronDown,ClipboardList,ShieldAlert} from 'lucide-react';
type Props={page:string;onNotice:(v:string)=>void};
export default function PJSOriginalPages({page,onNotice}:Props){
const [tab,setTab]=useState('Bill Submit');const [transport,setTransport]=useState('All transporters');const [status,setStatus]=useState('All statuses');const [selected,setSelected]=useState(false);
const notify=(action:string)=>onNotice(action+' is not connected in this OMS preview. Original PJS website and office worker remain unchanged.');
const isEmail=page==='Email Process',isTrack=page==='Tracking Delivery',isData=page==='Submit All Process';
const heading=isEmail?'Email to Client':isTrack?'Tracking Automation Console':isData?'DataDoc Submission Queue':'Check List';
return <div className='pjs-original'>
<div className='pjs-topline'><div><small>{isEmail?'STAGE 04 · CLIENT COMMUNICATION':isTrack?'STAGE 05 · DISPATCH TRACKING':isData?'STAGE 03 · DATADOC':'EXCEPTION DESK'}</small><h1>{heading}</h1><p>{isEmail?'Import the email queue from Excel. For each Process, upload the existing Outlook .eml conversation directly on that row. Continue Email opens that saved conversation on the office PC and starts Reply in Outlook.':isTrack?'Run, test and monitor transporter tracking from one screen. The website queues jobs; the office Python worker opens Chrome, reads the real carrier result, saves evidence and writes it back to Supabase.':isData?'Bill Submit handles the initial Credit / Non-Credit DataDoc transaction. Emails and Tracking are separate follow-up submissions.':'Manual exception handling stays under operator control. Resolve the issue, return it to Tracking, or close the process.'}</p></div>
{isEmail?<button className='pjs-blue' onClick={()=>document.getElementById('oms-email-excel')?.click()}><Upload size={15}/> Import Excel</button>:isTrack?<div className='pjs-actions'><button className='pjs-white' onClick={()=>document.getElementById('oms-track-excel')?.click()}><Upload size={15}/> Import Excel</button><button className='pjs-blue' onClick={()=>notify('Track Pending')}><RefreshCw size={15}/> Track Pending</button><button className='pjs-white' disabled> <PackageCheck size={15}/> Track Selected (0)</button><button className='pjs-white' disabled><AlertTriangle size={15}/> Retry Failed (0)</button><button className='pjs-white pjs-stop' disabled>Stop Queue</button></div>:isData?<div className='pjs-actions'><button className='pjs-blue' onClick={()=>notify('Submit Bills')}><FileCheck2 size={15}/> Submit Bills (0)</button><button className='pjs-white' onClick={()=>notify('Submit Emails')}><Mail size={15}/> Submit Emails (0)</button><button className='pjs-white pjs-mint' onClick={()=>notify('Submit Tracking')}><PackageCheck size={15}/> Submit Tracking (0)</button></div>:null}</div>
{(isEmail||isTrack)&&<input type='file' id={isEmail?'oms-email-excel':'oms-track-excel'} accept='.xlsx,.xls,.csv' hidden onChange={e=>{if(e.target.files?.length)onNotice('Selected '+e.target.files[0].name+'. Excel import to the PJS backend is not connected in this OMS preview.')}}/>}
{isTrack&&<><div className='pjs-metrics'><div className='pjs-metric pjs-worker'><small>PYTHON WORKER</small><b><i/> OFFLINE</b><span>Office worker not connected to OMS</span></div><div className='pjs-metric'><small>CURRENT PROCESS</small><b>—</b><span>Waiting for queue</span></div><div className='pjs-metric pjs-actionmetric'><small>CURRENT ACTION</small><strong>No tracking job running</strong><span>Ready</span></div><div className='pjs-metric'><small>QUEUE</small><b>0</b><span>0 waiting · 0 running</span></div></div><div className='pjs-two'><div className='pjs-panel'><h3>Tracking controls</h3><p>Filter the queue before selecting records.</p><div className='pjs-filter'><label>Transporter<select value={transport} onChange={e=>setTransport(e.target.value)}><option>All transporters</option><option>TCI</option><option>VExpress</option><option>DTDC</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Pending</option><option>In Transit</option><option>Delivered</option><option>RTO</option><option>Failed</option></select></label><div className='pjs-filterstat'>Visible<b>0</b></div><div className='pjs-filterstat'>Selected<b>0</b></div></div></div><div className='pjs-panel'><div className='pjs-panelhead'><div><h3>Needs Attention</h3><p>Tracking records that should not disappear inside the log.</p></div><button className='pjs-white' onClick={()=>notify('Open Check List from Tracking')}>Open Check List</button></div><div className='pjs-empty'>No tracking exceptions right now.</div></div></div><div className='pjs-panel pjs-bottom'><h3>Tracking records</h3><p>Select rows for batch tracking or run a one-process Test Track while we validate each carrier.</p><div className='pjs-tablewrap'><table><thead><tr><th><input aria-label='Select all' type='checkbox' checked={selected} onChange={e=>setSelected(e.target.checked)}/></th><th>Process</th><th>Party</th><th>Transporter</th><th>LR / Docket</th><th>Status</th><th>Last Checked</th><th>Result</th></tr></thead><tbody><tr><td colSpan={8} className='pjs-nodata'>No tracking records loaded in this preview.</td></tr></tbody></table></div></div></>}
{isEmail&&<div className='pjs-panel pjs-email'><h3>Email dispatch queue</h3><p>Upload the existing email conversation at the end of the correct Process row.</p><div className='pjs-empty'>No processes are waiting for client email.</div></div>}
{isData&&<><div className='pjs-datatabs'>{[['Bill Submit',FileCheck2],['Emails',Mail],['Tracking',PackageCheck]].map(([name,Icon]:any)=><button key={name} className={tab===name?'selected':''} onClick={()=>setTab(name)}><Icon size={17}/><b>{name}</b><span>0</span></button>)}</div><div className='pjs-panel pjs-datacard'><h3>{tab}</h3><div className='pjs-tablewrap'><table><thead><tr>{(tab==='Bill Submit'?['Process','Party Name','Invoice','Amount','Credit / Non-Credit','Invoice File','E-Invoice','E-Bill','DataDoc']:tab==='Emails'?['Process','Party Name','Invoice','Email','Attachments','DataDoc Status']:['Process','Party Name','Transporter','LR / Docket','Delivery Proof','DataDoc Status']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody><tr><td className='pjs-nodata' colSpan={tab==='Bill Submit'?9:6}>No {tab.toLowerCase()} records transferred to this OMS preview.</td></tr></tbody></table></div></div></>}
{!isEmail&&!isTrack&&!isData&&<div className='pjs-panel pjs-check'><h3>Exceptions</h3><div className='pjs-tablewrap'><table><thead><tr>{['Process','Customer','Transporter','Status','Reason','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody><tr><td colSpan={6} className='pjs-nodata'>No exceptions are loaded in this OMS preview.</td></tr></tbody></table></div></div>}
</div>;
}