import {Activity,AlertTriangle,ArrowRight,CheckCircle2,Clock3,Database,Download,FileCheck2,FileClock,PackageCheck,Save,ShieldCheck,Truck} from 'lucide-react';
import {Button,Empty,Heading,Panel,RecordsTable,Stat,Tone} from './UnifiedKit';
import ExcelLRWorkspace from './ExcelLRWorkspace';
import PendingChecks from './PendingChecks';
import {type Preferences,showDate,isException} from './unifiedOps';
import {useState} from 'react';
export default function UnifiedStagePagesB({page,p}:{page:string;p:any}){
 const {results,records,events,jobs,onEdit,onStage,onQueue,onExport,busy,onError,onNotice,demo,settings,setSettings}=p;
 const [saving,setSaving]=useState(false);
 if(page==='Delivery Proof'){
  const rows=results.filter((r:any)=>/delivered|delivery proof/i.test((r.status||'')+' '+(r.stage||'')));
  return <><Heading eyebrow='STAGE 06 · DELIVERY CONFIRMATION' title='Delivery Proof' description='Retain delivery evidence and queue the final proof for DataDoc after confirming delivered status.'/><Panel title='Delivered processes' subtitle='Never treat queued submissions as completed transactions.'><RecordsTable records={rows} onEdit={onEdit} renderAction={(r:any)=><><Button onClick={()=>onEdit(r)}>Evidence</Button><Button variant='primary' disabled={busy} onClick={()=>onQueue(r,'delivery_proof_submit')}>Queue proof</Button><Button variant='mint' disabled={busy} onClick={()=>onStage(r,'Complete','Complete')}>Close process</Button></>}/></Panel></>;
 }
 if(page==='Check List')return <><Heading eyebrow='EXCEPTION MANAGEMENT' title='Check List' description='RTO, failed tracking, document and address exceptions remain visible until an operator resolves them.'/><Panel title='Exceptions needing action' subtitle='Return to tracking or close with an audit event after confirming resolution.'><RecordsTable records={results.filter(isException)} onEdit={onEdit} renderAction={(r:any)=><><Button onClick={()=>onEdit(r)}>Review</Button><Button variant='primary' disabled={busy} onClick={()=>onStage(r,'Dispatch Tracking','Pending')}>Retry tracking</Button><Button variant='mint' disabled={busy} onClick={()=>onStage(r,'Complete','Complete')}>Resolve</Button></>}/></Panel></>;
 if(page==='Excel & LR Finder')return <><Heading eyebrow='DOCUMENT INTELLIGENCE' title='Excel & LR Finder' description='Read courier bills, extract LR / Docket numbers, and match them with stored PJS process records.'/><ExcelLRWorkspace records={records}/></>;
 if(page==='Pending Task Review')return <><Heading eyebrow='AUTOMATED COMPLETENESS CHECKS' title='Pending Task Review' description='Real-time document and field checks; AI-generated actions remain disabled until verified.'/><PendingChecks records={records} onOpen={onEdit}/></>;
 if(page==='Audit & Reports')return <><Heading eyebrow='OPERATIONS INTELLIGENCE' title='Audit & Reports' description='Review process transitions and automation requests. Worker execution status is never assumed.' actions={<Button onClick={onExport}><Download size={16}/> Export CSV</Button>}/><div className='ux-two-col'><Panel title='Recent workflow activity' subtitle='Cloud events from process changes.'>{events.length?<div className='ux-event-list'>{events.slice(0,35).map((e:any)=><div className='ux-event' key={e.id}><span><CheckCircle2 size={15}/></span><div><strong>{e.action}</strong><small>Process {e.process_no||'—'} · {showDate(e.created_at)}</small></div></div>)}</div>:<Empty icon={FileClock} title='No activity yet' help='Create or edit a process to start the cloud audit trail.'/></Panel><Panel title='Automation job queue' subtitle='Requests wait for the office PC automation worker.' actions={<span className='ux-offline'>WORKER NOT CONNECTED</span>}>{jobs.length?<div className='ux-job-list'>{jobs.slice(0,35).map((j:any)=><div className='ux-job' key={j.id}><div><strong>{String(j.job_type).replaceAll('_',' ')}</strong><small>{j.process_no} · {showDate(j.created_at)}</small></div><Tone value={j.status}/>{j.error_message&&<small className='ux-warning'>{j.error_message}</small>}</div>)}</div>:<Empty icon={Activity} title='No job requests' help='Approved tracking or DataDoc queue requests will be listed here.'/></Panel></div></>;
 if(page==='Settings')return <><Heading eyebrow='ADMINISTRATION' title='Workspace settings' description='Business rules saved securely per signed-in user in independent Supabase.'/><div className='ux-two-col'><Panel title='Dispatch rules' subtitle='Update reminder and E-Way Bill thresholds.'><div className='ux-settings-fields'><label className='ux-field'>E-Way Bill threshold (₹)<input type='number' min='0' value={settings.ebill_threshold} onChange={e=>setSettings({...settings,ebill_threshold:Number(e.target.value)})}/></label><label className='ux-field'>Re-track interval (days)<input type='number' min='1' max='90' value={settings.retrack_days} onChange={e=>setSettings({...settings,retrack_days:Number(e.target.value)})}/></label><label className='ux-field'>Reminder window (days)<input type='number' min='1' max='90' value={settings.reminder_days} onChange={e=>setSettings({...settings,reminder_days:Number(e.target.value)})}/></label><Button variant='primary' disabled={saving||demo} onClick={()=>{setSaving(true);void import('./unifiedOps').then(({ops})=>ops.updatePreferences(settings)).then(()=>onNotice('Settings saved to independent cloud.')).catch(e=>onError(e.message)).finally(()=>setSaving(false))}}><Save size={16}/> {saving?'Saving…':'Save settings'}</Button></div></Panel><Panel title='Independent infrastructure' subtitle='Clearly separated from the legacy PJS database.'><div className='ux-readiness'><div><span className='ux-ready-icon green'><ShieldCheck size={19}/></span><div><strong>Passwordless email login</strong><small>One-time link via Supabase Auth</small></div><b className='green'>Configured</b></div><div><span className='ux-ready-icon green'><Database size={19}/></span><div><strong>Private Postgres + storage</strong><small>Row-level protected process documents</small></div><b className='green'>Configured</b></div><div><span className='ux-ready-icon orange'><Activity size={19}/></span><div><strong>Office Python worker</strong><small>DataDoc, Outlook and carrier automation</small></div><b className='orange'>Awaiting setup</b></div></div></Panel></div></>;
 return null;
}
