import {Activity,AlertCircle,AlertTriangle,ArrowRight,ClipboardCheck,FileCheck2,FileUp,Mail,PackageCheck,RefreshCw,Search,Truck,Upload} from 'lucide-react';
import {Button,Empty,Heading,Panel,RecordsTable,SearchBar,Stat,Tone} from './UnifiedKit';
import {readyForBill} from './unifiedOps';
import {useState} from 'react';
export default function UnifiedStagePagesA({page,p}:{page:string;p:any}){
 const {results,records,jobs,onEdit,onGoto,onStage,onQueue,onAttach,onDraftEmail,search,setSearch,busy}=p;
 const [tab,setTab]=useState<'Bill Submit'|'Emails'|'Delivery Proof'>('Bill Submit');
 const [status,setStatus]=useState('All');
 if(page==='DataDoc'){
  const billRows=results.filter((r:any)=>r.stage!=='Complete');
  const emailRows=results.filter((r:any)=>/email|datadoc/i.test(r.stage||''));
  const deliveryRows=results.filter((r:any)=>/delivery proof|delivered/i.test((r.stage||'')+' '+(r.status||'')));
  const list=tab==='Bill Submit'?billRows:tab==='Emails'?emailRows:deliveryRows;
  return <><Heading eyebrow='STAGE 03 · DOCUMENT SUBMISSION' title='DataDoc Control' description='Initial bill submission, client email and delivery proof are three separate transactions. The office worker must confirm success.'/><div className='ux-tabs'>{(['Bill Submit','Emails','Delivery Proof'] as const).map((t,i)=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{i===0?<FileCheck2 size={17}/>:i===1?<Mail size={17}/>:<PackageCheck size={17}/>} {t} <b>{(i===0?billRows:i===1?emailRows:deliveryRows).length}</b></button>)}</div>
   <Panel title={tab==='Bill Submit'?'DataDoc Bill Submit':tab==='Emails'?'DataDoc Email Submit':'DataDoc Tracking Proof'} subtitle='Invoice PDF plus E-Invoice or E-Way Bill PDF is required for Bill Submit.' actions={<span className='ux-offline'><Activity size={14}/> OFFICE WORKER OFFLINE</span>}>
   <RecordsTable records={list} onEdit={onEdit} renderAction={(r:any)=><>{tab==='Bill Submit'?<><Button onClick={()=>onEdit(r)}>Validate</Button><Button variant='primary' disabled={!readyForBill(r)||busy} onClick={()=>onQueue(r,'bill_submit')}>Queue bill</Button></>:<Button variant='primary' disabled={busy} onClick={()=>onQueue(r,tab==='Emails'?'datadoc_submit':'delivery_proof_submit')}>Queue request</Button>}</>}/></Panel></>;
 }
 if(page==='Email to Client'){
  const rows=results.filter((r:any)=>/email|datadoc/i.test(r.stage||'')||Boolean(r.invoice));
  return <><Heading eyebrow='STAGE 04 · CLIENT COMMUNICATION' title='Email to Client' description='Prepare dispatch details, attach the existing Outlook email conversation, and queue a reply for the office agent.'/>
    <div className='ux-callout'><Mail size={19}/><span>Email drafts and files are stored in OMS. Actual Outlook sending remains disabled until the office Python worker is connected.</span></div>
    <div className='ux-card-list'>{rows.length?rows.map((r:any)=><article key={r.id} className='ux-process-card'><div className='ux-process-card-title'><div><strong>{r.process} · {r.party}</strong><small>SO {r.so||'—'} · Invoice {r.invoice||'Pending'} · {r.transporter||'Transporter pending'}</small></div><Tone value={r.stage}/></div><div className='ux-attachment-line'><Mail size={20}/><div><b>{(r.documents||[]).some((d:any)=>d.kind==='emailDoc')?'Outlook conversation attached':'Existing Outlook conversation needed'}</b><small>{(r.documents||[]).filter((d:any)=>d.kind==='emailDoc').map((d:any)=>d.name).join(', ')||'Attach the .eml conversation for this Process No.'}</small></div></div><div className='ux-row-actions'><Button onClick={()=>onDraftEmail(r)}><ClipboardCheck size={15}/> Copy dispatch draft</Button><label className='ux-button secondary ux-file-button'><Upload size={15}/> Upload .eml<input type='file' accept='.eml,message/rfc822' onChange={e=>{onAttach(r,'emailDoc',e.target.files?.[0]);e.target.value=''}}/></label><Button onClick={()=>onEdit(r)}>Edit</Button><Button variant='primary' disabled={busy||!(r.documents||[]).some((d:any)=>d.kind==='emailDoc')} onClick={()=>onQueue(r,'email_reply')}>Queue Outlook reply</Button><Button variant='mint' onClick={()=>onStage(r,'Dispatch Tracking','Pending')}>To tracking <ArrowRight size={14}/></Button></div></article>):<Empty icon={Mail} title='No email-ready processes' help='Complete invoice details and move a process to Email to Client first.'/></div></>;
 }
 if(page==='Dispatch Tracking'){
  const rows=results.filter((r:any)=>status==='All'||(r.status||'Pending')===status);
  const queue=jobs.filter((j:any)=>j.job_type==='tracking'&&['queued','running'].includes(j.status));
  return <><Heading eyebrow='STAGE 05 · TRANSPORTER AUTOMATION' title='Dispatch Tracking' description='Find courier consignments, queue carrier checks, and route returned or delayed deliveries to the exception desk.' actions={<Button onClick={()=>onGoto('Audit & Reports')}><Activity size={15}/> View queue</Button>}/>
   <div className='ux-stats compact'><Stat label='Transporter entries' icon={Truck} value={records.filter((r:any)=>r.transporter&&r.lr).length} note='Carrier + LR available'/><Stat label='Tracking requests' icon={RefreshCw} tone='orange' value={queue.length} note='Awaiting Python worker'/><Stat label='Exceptions' icon={AlertTriangle} tone='red' value={records.filter((r:any)=>/exception|rto|returned|delay/i.test((r.status||'')+' '+(r.stage||''))).length} note='Check List intervention'/></div>
   <Panel title='Tracking records' subtitle='Real carrier results require office-side Chrome automation.' actions={<span className='ux-offline'><Activity size={14}/> WORKER NOT CONNECTED</span>}><SearchBar value={search} onChange={setSearch} count={rows.length}/><div className='ux-tracking-filter'><label>Filter status <select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Pending</option><option>In Transit</option><option>Delivered</option><option>Exception</option></select></label></div><div className='ux-tablewrap'><table className='ux-table'><thead><tr><th>Process</th><th>Transporter</th><th>LR / Docket</th><th>Status</th><th>Stage</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id}><td><button className='ux-process-link' onClick={()=>onEdit(r)}>{r.process}</button><small>{r.party}</small></td><td>{r.transporter||<span className='ux-warning'>Missing</span>}</td><td>{r.lr||<span className='ux-warning'>Missing</span>}</td><td><Tone value={r.status}/></td><td>{r.stage||'Universal Process'}</td><td><div className='ux-action-flex'><Button onClick={()=>onEdit(r)}>Edit</Button><Button variant='primary' disabled={busy||!r.transporter||!r.lr} onClick={()=>onQueue(r,'tracking')}>Queue track</Button></div></td></tr>):<tr><td colSpan={6}><Empty icon={Truck} title='No tracking records' help='Enter a transporter and LR number in Universal Process.'/></td></tr>}</tbody></table></div></Panel></>;
 }
 return null;
}
