import {AlertTriangle,ArrowRight,CheckCircle2,ChevronRight,FileSearch,FileText,Inbox,Search} from 'lucide-react';
export function Tone({value}:{value:any}){const text=String(value||'Pending');const color=/complete|delivered|success|ready|verified/i.test(text)?'green':/error|exception|failed|rto|delayed|check list/i.test(text)?'red':/tracking|email|transit|running/i.test(text)?'blue':'amber';return <span className={'ux-tone '+color}><i/>{text}</span>}
export function Empty({title,help,icon:Icon=Inbox}:{title:string;help:string;icon?:any}){return <div className='ux-empty'><span><Icon size={23}/></span><strong>{title}</strong><small>{help}</small></div>}
export function Button({children,onClick,variant='secondary',disabled=false}:{children:any;onClick?:()=>void;variant?:string;disabled?:boolean}){return <button type='button' className={'ux-button '+variant} onClick={onClick} disabled={disabled}>{children}</button>}
export function Stat({label,value,note,icon:Icon,tone='blue'}:{label:string;value:any;note:string;icon:any;tone?:string}){return <div className='ux-stat'><div><span>{label}</span><b className={'ux-stat-symbol '+tone}><Icon size={18}/></b></div><strong>{value}</strong><small>{note}</small></div>}
export function Heading({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:any}){return <div className='ux-page-heading'><div><span className='ux-kicker dark'>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions&&<div className='ux-page-actions'>{actions}</div>}</div>}
export function Panel({title,subtitle,actions,children}:{title:string;subtitle?:string;actions?:any;children:any}){return <section className='ux-panel'><div className='ux-panel-title'><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{actions}</div>{children}</section>}
export function RecordsTable({records,onEdit,renderAction}:{records:any[];onEdit:(r:any)=>void;renderAction?:(r:any)=>any}){return <div className='ux-tablewrap'><table className='ux-table'><thead><tr><th>Process</th><th>Party name</th><th>SO No.</th><th>Stage</th><th>Docs</th><th>Status</th><th>Action</th></tr></thead><tbody>{records.length?records.map(r=><tr key={r.id}><td><button className='ux-process-link' onClick={()=>onEdit(r)}>{r.process}</button></td><td><strong>{r.party||'—'}</strong><small>{r.invoice?'Invoice '+r.invoice:'Invoice optional for Email'}</small></td><td>{r.so||'—'}</td><td><span className='ux-stage-tag'>{r.stage||'Universal Process'}</span></td><td><span className='ux-doc-count'><FileText size={13}/>{(r.documents||[]).length}</span>{(r.documents||[]).some((d:any)=>d.kind==='donePickDoc')&&<small className='ux-done-chip'><CheckCircle2 size={12}/> Done Pick List</small>}</td><td><Tone value={r.status}/></td><td><div className='ux-action-flex'>{renderAction?.(r)||<Button onClick={()=>onEdit(r)}>Open <ChevronRight size={14}/></Button>}</div></td></tr>):<tr><td colSpan={7}><Empty icon={FileSearch} title='No matching processes' help='Upload a Pick Slip or try a different search.'/></td></tr>}</tbody></table></div>}
export function SearchBar({value,onChange,count,placeholder='Search Process No., Party, SO, invoice or LR…'}:{value:string;onChange:(v:string)=>void;count:number;placeholder?:string}){return <div className='ux-searchbar'><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange('')} aria-label='Clear search'>×</button>}<small>{count} result{count===1?'':'s'}</small></div>}
export const steps=[['01','Pick Slip','Intake'],['02','Universal','Verify'],['03','DataDoc','Bill Submit'],['04','Client Email','Dispatch'],['05','Tracking','Courier'],['06','Done Pick List','Photos'],['07','Complete','Close']];
