import {Activity,AlertTriangle,ArrowRight,CheckCircle2,ChevronRight,Clock3,Cloud,Database,Download,FileCheck2,FileClock,FileText,FileUp,Inbox,PackageCheck,Plus,RefreshCw,ShieldCheck,Sparkles,Truck,Upload} from 'lucide-react';
import {Button,Empty,Heading,Panel,RecordsTable,SearchBar,Stat,Tone,steps} from './UnifiedKit';
import {missingDocs,readyForBill} from './unifiedOps';
import {useState} from 'react';

export default function UnifiedCorePages({page,p}:{page:string;p:any}){
 const {records,trashedProcesses=[],onRestoreProcess,results,stats,onEdit,onImport,onDonePick,onNew,onExport,onGoto,onStage,search,setSearch,jobs,demo,busy}=p;
 const [showDeleted,setShowDeleted]=useState(false);
 if(page==='Control Tower'){
  const pending=(jobs||[]).filter((j:any)=>['queued','running'].includes(j.status));
  return <>
   <section className='ux-hero'><div className='ux-hero-copy'><span className='ux-kicker light'><Sparkles size={15}/> DISPATCH COMMAND CENTER</span><h1>One system. <em>Every dispatch under control.</em></h1><p>From the first Pick Slip through DataDoc, emails, courier tracking and final delivery confirmation—all in one independent workspace.</p><div className='ux-hero-buttons'><Button variant='white' onClick={onImport}><Upload size={17}/> Upload Pick Slip</Button><Button variant='ghost-light' onClick={onDonePick}><FileCheck2 size={16}/> Done Pick List Photo</Button><Button variant='ghost-light' onClick={()=>onGoto('Universal Process')}>Open process workspace <ArrowRight size={17}/></Button></div></div><div className='ux-hero-visual'><div className='ux-hero-circle'><Activity size={50}/></div><div>DISPATCH FLOW<br/>CONNECTED</div></div></section>
   <div className='ux-stats'><Stat icon={Database} label='Total processes' value={stats.total} note={demo?'This browser only':'Cloud process master'}/><Stat icon={Clock3} label='In workflow' value={stats.total-stats.complete} note='Active dispatch files' tone='purple'/><Stat icon={AlertTriangle} label='Needs attention' value={stats.pending} note='Document / field gaps' tone='orange'/><Stat icon={CheckCircle2} label='Completed' value={stats.complete} note='Closed processes' tone='green'/></div>
   <Panel title='Dispatch journey' subtitle='PJS operations workflow, combined with the modern OMS document model.' actions={<span className='ux-caption'>7 STAGES</span>}><div className='ux-journey'>{steps.map(([no,title,sub],i)=><div className='ux-step' key={no}><span>{no}</span><b>{title}</b><small>{sub}</small>{i<steps.length-1&&<ArrowRight size={14}/>}</div>)}</div></Panel>
   <div className='ux-two-col'><Panel title='Recent processes' subtitle='Continue where each dispatch last stopped.' actions={<button className='ux-link' onClick={()=>onGoto('Universal Process')}>View all <ArrowRight size={14}/></button>}>{records.length?records.slice(0,6).map((r:any)=><button className='ux-recent' key={r.id} onClick={()=>onEdit(r)}><span className='ux-recent-icon'><FileText size={17}/></span><span className='ux-recent-name'><strong>{r.process} <span>· {r.party}</span></strong><small>SO {r.so||'—'} · {r.transporter||'Transporter pending'}</small></span><Tone value={r.stage}/><ChevronRight size={16}/></button>):<Empty icon={Inbox} title='Start with a Pick Slip' help='Click Upload Pick Slip to create your first process record.'/>}</Panel>
   <Panel title='System readiness' subtitle='Live infrastructure versus automation still awaiting setup.'><div className='ux-readiness'><div><span className='ux-ready-icon green'><Cloud size={19}/></span><div><strong>Independent Supabase</strong><small>Owner-scoped database and RLS</small></div><b className={demo?'orange':'green'}>{demo?'Not signed in':'Connected'}</b></div><div><span className='ux-ready-icon green'><ShieldCheck size={19}/></span><div><strong>Private document storage</strong><small>Pick Slips, invoices and LR documents</small></div><b className={demo?'orange':'green'}>{demo?'Not in use':'Configured'}</b></div><div><span className='ux-ready-icon orange'><Activity size={19}/></span><div><strong>Office Python worker</strong><small>DataDoc, Outlook, carrier browser automation</small></div><b className='orange'>Not connected</b></div><div><span className='ux-ready-icon orange'><FileClock size={19}/></span><div><strong>Queued jobs</strong><small>{pending.length} request(s) waiting; no execution implied</small></div><b className='orange'>Waiting</b></div></div></Panel></div>
  </>;
 }
 if(page==='Data Store')return <>
  <Heading eyebrow='DOCUMENT MANAGEMENT' title='Data Store' description={demo?'Upload a Pick Slip to read its fields; process details stay on this browser and original PDFs are NOT saved.':'Upload and verify a Pick Slip to create a process. Keep all related documents under that Process No.'} actions={<><Button onClick={onNew}><Plus size={16}/> Manual process</Button><Button variant='primary' onClick={onImport}><FileUp size={17}/> Upload Pick Slip</Button><Button onClick={onDonePick}><FileCheck2 size={16}/> Upload Done Pick List</Button></>}/>
  <div className='ux-stats compact'><Stat label='Total processes' value={stats.total} note='Independent OMS' icon={Database}/><Stat label='Stored Pick Slips' value={records.filter((r:any)=>(r.documents||[]).some((d:any)=>d.kind==='pickDoc')).length} note={demo?'PDF not saved here':'Original PDF retained'} icon={FileCheck2} tone='green'/><Stat label='Done Pick Lists' value={records.filter((r:any)=>(r.documents||[]).some((d:any)=>d.kind==='donePickDoc')).length} note={demo?'Available after cloud login':'Matched photo attached'} icon={FileCheck2} tone='purple'/><Stat label='Ready for email stage' value={records.filter((r:any)=>r.stage==='Email to Client').length} note='Invoice files not required' icon={FileCheck2} tone='green'/></div>
  <Panel title='Process documents' subtitle='Each process is identified by Process No., Party Name and SO No.' actions={<span className='ux-caption'>{results.length} RECORDS</span>}><SearchBar value={search} onChange={setSearch} count={results.length}/><RecordsTable records={results} onEdit={onEdit}/></Panel>
  {!demo&&<section className='ux-master-trash-list'>
   <button type='button' onClick={()=>setShowDeleted(!showDeleted)}><FileClock size={16}/> {showDeleted?'Hide Deleted Processes':'Deleted Processes (Trash)'} <small>{trashedProcesses.length} recoverable</small></button>
   {showDeleted&&<div>{trashedProcesses.length?trashedProcesses.map((r:any)=><div key={r.id}>
    <span><strong>Process {r.process}</strong><small>{r.party||'Unknown party'} · {(r.documents||[]).length} document(s) preserved</small></span>
    <Button disabled={busy} onClick={()=>void onRestoreProcess(r)}><RefreshCw size={14}/> Restore</Button>
   </div>):<p>No deleted personal processes.</p>}</div>}
  </section>}
 </>;
 if(page==='Universal Process')return <>
  <Heading eyebrow='STAGE 02 · MASTER PROCESS' title='Universal Process' description='Maintain the Process No. and documents. Invoice details are optional for moving to Email to Client.' actions={<><Button onClick={onExport}><Download size={16}/> Export CSV</Button><Button variant='primary' onClick={onImport}><FileUp size={16}/> Upload Pick Slip</Button><Button onClick={onDonePick}><FileCheck2 size={16}/> Done Pick List</Button></>}/>
  <Panel title='Process register' subtitle='Moving a verified process to Email does not require invoice, E-Invoice or E-Way Bill attachments.' actions={<Button onClick={onNew}><Plus size={16}/> New process</Button>}><SearchBar value={search} onChange={setSearch} count={results.length}/><RecordsTable records={results} onEdit={onEdit} renderAction={(r:any)=><><Button onClick={()=>onEdit(r)}>Edit</Button><Button variant='mint' disabled={busy} onClick={()=>onStage(r,'Email to Client','Ready for Email')}>Move to Email <ArrowRight size={13}/></Button></>}/></Panel>
 </>;
 return null;
}
