import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,LockKeyhole,Mail,ShieldCheck,AlertCircle,LayoutDashboard,Sparkles} from 'lucide-react';
import {supabase} from './independentClient';
export default function UnifiedLogin({onDemo}:{onDemo:()=>void}){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!cooldown)return;const t=setTimeout(()=>setCooldown(false),60000);return()=>clearTimeout(t)},[cooldown]);
 async function send(){
  if(!supabase){setMessage('Cloud configuration unavailable.');return}
  if(!email.includes('@')){setMessage('Please enter a valid email address.');return}
  setBusy(true);setMessage('');
  try{const {error}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:window.location.origin,shouldCreateUser:true}});
   if(error)throw error;setSent(true);setCooldown(true);
  }catch(e:any){const m=String(e?.message||'');setMessage(e?.status===429||/rate.?limit/i.test(m)?'Email requests are temporarily limited. Wait a few minutes and try again.':/not authorized/i.test(m)?'This email is not authorized by the default Supabase sender. Your administrator needs custom SMTP for non-team addresses.':m||'Unable to send approval email.')}
  finally{setBusy(false)}
 }
 async function verify(){if(!supabase)return;setBusy(true);setMessage('');try{const {error}=await supabase.auth.verifyOtp({email:email.trim().toLowerCase(),token:code,type:'email'});if(error)throw error;}catch(e:any){setMessage(e?.message||'Verification failed')}finally{setBusy(false)}}
 return <div className='ux-auth'><div className='ux-auth-brand'><div className='ux-biglogo'>P</div><div><strong>PJS <i>Operations</i></strong><small>THE UNIFIED CONTROL SYSTEM</small></div></div><div className='ux-auth-left'><div className='ux-kicker'><Sparkles size={16}/> ALL OPERATIONS. ONE WORKSPACE.</div><h1>From Pick Slip to <em>delivery proof.</em></h1><p>A single place for PJS dispatch, DataDoc, client communication, transporter tracking, process records and cloud documents.</p><div className='ux-features'><span><CheckCircle2 size={17}/> Unified process management</span><span><CheckCircle2 size={17}/> Private file storage</span><span><CheckCircle2 size={17}/> DataDoc & carrier queues</span><span><CheckCircle2 size={17}/> Audit and exceptions</span></div></div><div className='ux-auth-right'><div className='ux-login-card'><div className='ux-lock'><LockKeyhole size={23}/></div><div className='ux-kicker dark'>SECURE ACCESS</div><h2>{sent?'Check your email':'Welcome back'}</h2><p>{sent?'Click the approval link in your latest login email. You will return to OMS automatically.':'Sign in without a password. We will email you a secure one-time approval link.'}</p><label className='ux-field'>Work email<input type='email' autoComplete='email' placeholder='you@company.com' value={email} disabled={sent} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}}/></label>{sent?<><div className='ux-sent'><Mail size={18}/> Email requested for <strong>{email}</strong></div><button className='ux-primary ux-full' disabled={busy||cooldown} onClick={()=>void send()}>{cooldown?'Wait before resending':'Resend approval email'} <ArrowRight size={16}/></button><div className='ux-codehelp'><small>If your email contains a numeric verification code:</small><div><input placeholder='Email code' inputMode='numeric' value={code} maxLength={8} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button onClick={()=>void verify()} disabled={busy||code.length<6}>Verify</button></div></div><button className='ux-link' onClick={()=>{setSent(false);setMessage('')}}>Change email</button></>:<button className='ux-primary ux-full' disabled={busy} onClick={()=>void send()}>{busy?'Sending…':'Send approval email'} <ArrowRight size={17}/></button>}{message&&<div className='ux-auth-error' role='alert'><AlertCircle size={16}/>{message}</div>}<div className='ux-divider'>OR</div><button className='ux-demo-btn' onClick={onDemo}><LayoutDashboard size={16}/> View design preview <ArrowRight size={16}/></button><div className='ux-auth-foot'><ShieldCheck size={15}/> Sign-in email delivery depends on your Supabase SMTP configuration.</div></div></div></div>;
}
