import {Activity,AlertTriangle,BarChart3,Bell,Bot,ChevronRight,ClipboardCheck,Cloud,Database,FileCheck2,Images,FileSpreadsheet,LayoutDashboard,LogOut,LogIn,Mail,Menu,PackageCheck,RefreshCw,Settings2,ShieldCheck,Truck,UserRound,X} from 'lucide-react';
import {type ReactNode,useState} from 'react';
export type Section='Control Tower'|'Data Store'|'Universal Process'|'DataDoc'|'Email to Client'|'Dispatch Tracking'|'Done Pick List'|'Check List'|'Excel & LR Finder'|'Pending Task Review'|'Audit & Reports'|'Settings';
const nav:{name:string;items:[Section,any][]}[]=[
 {name:'COMMAND CENTER',items:[['Control Tower',LayoutDashboard],['Data Store',Database],['Universal Process',ClipboardCheck]]},
 {name:'DISPATCH WORKFLOW',items:[['DataDoc',FileCheck2],['Email to Client',Mail],['Dispatch Tracking',Truck],['Done Pick List',Images],['Check List',AlertTriangle]]},
 {name:'INTELLIGENCE & TOOLS',items:[['Excel & LR Finder',FileSpreadsheet],['Pending Task Review',Bot],['Audit & Reports',BarChart3],['Settings',Settings2]]},
];
export default function UnifiedShell({page,onPage,onRefresh,onSignOut,demo,user,stats,busy,children}:{page:Section;onPage:(p:Section)=>void;onRefresh:()=>void;onSignOut:()=>void;demo:boolean;user:any;stats:any;busy:boolean;children:ReactNode}){
 const [mobile,setMobile]=useState(false);
 function go(p:Section){onPage(p);setMobile(false)}
 return <div className='ux-shell'><aside className={'ux-sidebar '+(mobile?'mobile-open':'')}>
  <div className='ux-brand'><div className='ux-logo'>P</div><div><strong>PJS <i>Operations</i></strong><small>UNIFIED CONTROL SYSTEM</small></div><button className='ux-mobile-close' onClick={()=>setMobile(false)}><X size={20}/></button></div>
  <nav className='ux-side-menu'>{nav.map(g=><div className='ux-nav-group' key={g.name}><div className='ux-nav-heading'>{g.name}</div>{g.items.map(([id,Icon])=><button className={'ux-nav-btn '+(page===id?'active':'')} key={id} onClick={()=>go(id)}><Icon size={18}/><span>{id}</span>{id==='Check List'&&stats.exceptions>0&&<b>{stats.exceptions}</b>}{id==='Pending Task Review'&&stats.pending>0&&<b>{stats.pending}</b>}</button>)}</div>)}</nav>
  <div className='ux-side-bottom'><div className='ux-worker-card'><span/><div><b>Office worker offline</b><small>Real carrier and DataDoc automation not connected</small></div></div><div className='ux-account'><div className='ux-account-avatar'><UserRound size={17}/></div><div><b>{demo?'Local preview':user?.email?.split('@')[0]||'OMS User'}</b><small>{demo?'This browser only':'Private workspace'}</small></div><button onClick={onSignOut} title={demo?'Sign in to cloud':'Sign out'} aria-label={demo?'Sign in to cloud':'Sign out'}>{demo?<LogIn size={18}/>:<LogOut size={18}/>}</button></div></div>
 </aside>
 {mobile&&<button className='ux-mobile-scrim' onClick={()=>setMobile(false)} aria-label='Close navigation'/>}
 <main className='ux-main'><header className='ux-topbar'><div className='ux-crumb'><button className='ux-mobile-menu' aria-label='Open menu' onClick={()=>setMobile(true)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={15}/><strong>{page}</strong></div><div className='ux-top-actions'><span className={'ux-online '+(demo?'preview':'')}><i/>{demo?'LOCAL ONLY':'PRIVATE CLOUD'}</span><button onClick={onRefresh} disabled={busy} aria-label='Refresh'><RefreshCw size={18} className={busy?'ux-spin':''}/></button><button onClick={()=>go('Pending Task Review')} aria-label='Pending tasks'><Bell size={18}/>{stats.pending>0&&<i className='ux-notification-dot'/>}</button><div className='ux-top-avatar'>{demo?'D':(user?.email?.[0]||'P').toUpperCase()}</div></div></header>
 <div className='ux-content'><div className={'ux-context-strip '+(demo?'preview':'')}><ShieldCheck size={16}/>{demo?'NO LOGIN · Process fields saved in this browser only. PDF files, cloud backups, emails and automation are NOT saved or executed.':'INDEPENDENT WORKSPACE · Private cloud records and attachments, shared only with authorized team members.'}</div>{children}<footer className='ux-footer'><span><ShieldCheck size={15}/> PJS Operations · Independent OMS</span><span>Original PJS site unchanged · Vercel + Supabase</span></footer></div></main></div>;
}
